In [1]:
import numpy as np

In [2]:
#Affineクラスの実装
class Affine:
    def __init__(self,W,b):
        self.W = W
        self.b = b
        self.x = None
        self.dW = None
        self.db = None
    
    #順伝播の値を格納
    def forward(self,x):
        self.x = x
        a = np.dot(x,self.W) + self.b
        return a
    
    #逆伝播で得られた偏微分の値を格納
    #dW = 重みの偏微分
    #db = バイアスの偏微分
    def backward(self,dout):
        dx = np.dot(dout,self.W.T) 
        self.dW = np.dot(self.x.T,dout)
        self.db = dout
        return dx

In [3]:
#Affineクラスのテスト
import sys,os
sys.path.append(os.pardir)
from datasets.mnist import load_mnist

(x_train,t_train),(x_test,t_test) = load_mnist(normalize= True, one_hot_label = True)

#訓練データのパラメータの数

In [6]:
#np配列の設定を確認
np.get_printoptions()
#np配列の小数点の桁数を3桁に設定
np.set_printoptions(precision = 2)

#重みWの値をランダムに設定
w = np.random.randn(x_train.shape[1],x_train.shape[0])

In [7]:
#バイアスbの値をランダムに設定
b = np.random.randn(x_train.shape[1],x_train.shape[0])
print(b)

[[-0.16  0.9   0.58 ... -0.89 -0.04  1.68]
 [ 1.44  0.43  2.76 ... -0.99  1.02  0.6 ]
 [-0.72  1.19  0.9  ... -1.09 -0.04  1.41]
 ...
 [ 0.52 -1.19 -0.66 ...  0.31 -0.36  2.1 ]
 [-1.27 -0.69  0.76 ...  3.13  1.66  1.46]
 [ 1.56  0.6   0.78 ... -0.84  1.17 -0.14]]


In [8]:
#テスト用データ
affine = Affine(w,b)

In [9]:
#テスト用データの実装
affine.forward(x_train)

MemoryError: 